### ISSUE TITLE
兄弟们有弄成功的吗

### ISSUE THREAD

**Issue by coolerpluto** [NB-Dragon/SheepSolver#1]

**Comment by leeso2021** [comment]
有的 要看运气 卡了一分钟就直接放弃吧

**Comment by longhuan1999** [comment]
我这5分钟内求解成功目前只有两次，还有两次5分钟内跑完但返回无解。
在这顺便分享下我整合了[NB-Dragon/SheepSolver](https://github.com/NB-Dragon/SheepSolver)算法的在线3D地图PHP版：[longhuan1999/sheep](https://github.com/longhuan1999/sheep/tree/autoSolver-php)

**Comment by duqian42707** [comment]
成功了一次，用时12.24秒

**Comment by leeso2021** [comment]
今天的运气不行了。。。

**Comment by longhuan1999** [comment]
可以用多线程进行优化，但就是不清楚怎么对路径进行分组好

**Comment by f13098804603** [comment]
今天算法跑死都跑不出来

**Comment by coolerpluto** [comment]
作者优化一下，作者威武霸气

**Comment by NB-Dragon** [comment]
> 我这5分钟内求解成功目前只有两次，还有两次5分钟内跑完但返回无解。 在这顺便分享下我整合了[NB-Dragon/SheepSolver](https://github.com/NB-Dragon/SheepSolver)算法的在线3D地图PHP版：[longhuan1999/sheep](https://github.com/longhuan1999/sheep/tree/autoSolver-php)

你这什么电脑啊，竟然能让程序提示无解，我跑完16G内存电脑死机了都还没出现无解的提示

**Comment by NB-Dragon** [comment]
> 

多线程无法优化，因为单线程都已经跑完100%CPU了，除非分布式。但就如你所说，如何分割任务是个难题

**Comment by NB-Dragon** [comment]
> 

多线程无法优化，因为单线程都已经跑完100%CPU了，除非分布式。但就如你所说，如何分割任务是个难题

**Comment by longhuan1999** [comment]
> > 我这5分钟内求解成功目前只有两次，还有两次5分钟内跑完但返回无解。 在这顺便分享下我整合了[NB-Dragon/SheepSolver](https://github.com/NB-Dragon/SheepSolver)算法的在线3D地图PHP版：[longhuan1999/sheep](https://github.com/longhuan1999/sheep/tree/autoSolver-php)
> 
> 你这什么电脑啊，竟然能让程序提示无解，我跑完16G内存电脑死机了都还没出现无解的提示

可能踩了狗屎运，遇到了一来始就无解的关卡。我也觉得短时间内跑不出解就不用等了，还是重新来一关碰碰运气

**Comment by hackermengzhi** [comment]
只有撤销移除没有其他选项是否为无解？
