### ISSUE TITLE
直接运行后报错

### ISSUE THREAD

**Issue by anymine94** [NB-Dragon/SheepSolver#10]
您好，我抓包后运行会直接显示
Addon error: Traceback (most recent call last):
  File "automatic/DataAnalyzer.py", line 13, in response
    self._map_data_helper.update_map_data(flow.response.content, "normal")
  File "D:\sheep\Solver\SheepSolver\automatic\MapDataHelper.py", line 37, in update_map_data
    self._generate_final_map_data(map_cache_data)
  File "D:\sheep\Solver\SheepSolver\automatic\MapDataHelper.py", line 57, in _generate_final_map_data
    block_type_list = self._generate_shuffle_list(map_cache_data["blockTypeData"])
  File "D:\sheep\Solver\SheepSolver\automatic\MapDataHelper.py", line 81, in _generate_shuffle_list
    return self._javascript_execute.call("shuffle", block_type_list, self._random_seed)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: ReferenceError: shuffle is not defined
这样报错，文件目录结构没有改变过，导致不能生成online_data.json这个文件，我应该怎么修改内容呢

**Comment by Caipto** [comment]
> 您好，我抓包后运行会直接显示 Addon error: Traceback (most recent call last): File "automatic/DataAnalyzer.py", line 13, in response self._map_data_helper.update_map_data(flow.response.content, "normal") File "D:\sheep\Solver\SheepSolver\automatic\MapDataHelper.py", line 37, in update_map_data self._generate_final_map_data(map_cache_data) File "D:\sheep\Solver\SheepSolver\automatic\MapDataHelper.py", line 57, in _generate_final_map_data block_type_list = self._generate_shuffle_list(map_cache_data["blockTypeData"]) File "D:\sheep\Solver\SheepSolver\automatic\MapDataHelper.py", line 81, in _generate_shuffle_list return self._javascript_execute.call("shuffle", block_type_list, self._random_seed) File "C:\Users\ZQY\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs_abstract_runtime_context.py", line 37, in call return self._call(name, *args) File "C:\Users\ZQY\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs_external_runtime.py", line 92, in _call return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args)) File "C:\Users\ZQY\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs_external_runtime.py", line 78, in _eval return self.exec_(code) File "C:\Users\ZQY\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs_abstract_runtime_context.py", line 18, in exec_ return self._exec_(source) File "C:\Users\ZQY\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs_external_runtime.py", line 88, in _exec_ return self._extract_result(output) File "C:\Users\ZQY\AppData\Local\Programs\Python\Python310\lib\site-packages\execjs_external_runtime.py", line 167, in _extract_result raise ProgramError(value) execjs._exceptions.ProgramError: ReferenceError: shuffle is not defined 这样报错，文件目录结构没有改变过，导致不能生成online_data.json这个文件，我应该怎么修改内容呢

今天是跑不出来的 今天这么难

**Comment by NB-Dragon** [comment]
@anymine94 按照说明提示按步骤走就不会出错

**Comment by wurenzaiting** [comment]
以上报错同问

**Comment by anymine94** [comment]
> @anymine94 按照说明提示按步骤走就不会出错
您好，我又试了一次，还是报错
第十三行修改成这样self._code_entrance_path = "D:\SheepSolver"
系统环境变量添加了PYTHONPATH=D:\SheepSolver
还有什么地方要修改吗

**Comment by leeso2021** [comment]
一样的问题，shuffle未定义，pyexejs执行的时候报错。。。

**Comment by leeso2021** [comment]
还有个问题，结果出来后 怎么用dataposter提交啊。。。。

**Comment by NB-Dragon** [comment]
> 还有个问题，结果出来后 怎么用dataposter提交啊。。。。

该功能属于尝鲜功能，暂时不公开使用教程。建议搭配3D可视化使用

**Comment by NB-Dragon** [comment]
> > @anymine94 按照说明提示按步骤走就不会出错
> > 您好，我又试了一次，还是报错
> > 第十三行修改成这样self._code_entrance_path = "D:\SheepSolver"
> > 系统环境变量添加了PYTHONPATH=D:\SheepSolver
> > 还有什么地方要修改吗

路径得用双发斜杠

**Comment by wurenzaiting** [comment]
已解决！ windws为例 12行：self._code_entrance_path ="/Users/Administrator/SheepSolver"
临时变量：$env:PYTHONPATH="C:\Users\Administrator\SheepSolver"
huffle未定义 问题 已解决， helper\FileHelper.py 18行 改为 “reader = open(file_path, "r", encoding="utf-8")”

**Comment by anymine94** [comment]
> 已解决！ windws为例 12行：self._code_entrance_path ="/Users/Administrator/SheepSolver" 临时变量：$env:PYTHONPATH="C:\Users\Administrator\SheepSolver" huffle未定义 问题 已解决， helper\FileHelper.py 18行 改为 “reader = open(file_path, "r", encoding="utf-8")”



> 已解决！ windws为例 12行：self._code_entrance_path ="/Users/Administrator/SheepSolver" 临时变量：$env:PYTHONPATH="C:\Users\Administrator\SheepSolver" huffle未定义 问题 已解决， helper\FileHelper.py 18行 改为 “reader = open(file_path, "r", encoding="utf-8")”

感谢

**Comment by anymine94** [comment]
> > > @anymine94 按照说明提示按步骤走就不会出错
> > > 您好，我又试了一次，还是报错
> > > 第十三行修改成这样self._code_entrance_path = "D:\SheepSolver"
> > > 系统环境变量添加了PYTHONPATH=D:\SheepSolver
> > > 还有什么地方要修改吗
> 
> 路径得用双发斜杠

好的，谢谢
