### ISSUE TITLE
关于算法优化的几个想法

### ISSUE THREAD

**Issue by jiangyanfeng** [NB-Dragon/SheepSolver#11]
通过对回溯中间过程的回放，以及计算资源使用情况，我有以下建议：
1. 使用多线程回溯。目前电脑的CPU空置率太高，最起码要把CPU跑到90%。
2. 需要支持道具的使用。有可能不使用道具本身就是无解的。
3. 回溯时，优先深牌区及深牌区本身能三消的情况。top-first 模式没有优先深牌区本身能三消的情况。

**Comment by NB-Dragon** [comment]
1：单线程已经跑满100%，无法优化。你可以多开几个模式同时跑，就能总CPU利用率90%
2：算法本质不用道具
3：任意模式都支持进度80%开始优先三消，你可以在程序入口进行修改
