### ISSUE TITLE
关于获取地图数据的建议

### ISSUE THREAD

**Issue by fmz200** [NB-Dragon/SheepSolver#12]
目前获取地图数据需要安装证书并配置代理等一系列操作步骤，是否考虑过参考SheepASheepV2项目直接根据token直接获取地图数据并保存到文件中，目前的代码来看修改幅度并不大。

**Comment by NB-Dragon** [comment]
如果你有仔细研读文档和代码，估计你会发现，这个项目分成了两部分。一部分是通过配置代理抓包获取地图数据并保存到本地，另一部分是根据地图数据进行求解。直接给一个token的话，我相信大多数用户都不知道怎么获取，我还不如直接将获取的方法写出来，跟项目融合到一起，静默状态下完成数据获取和计算。

**Comment by fmz200** [comment]
> Quote reply
我不会Python，但大致思路如下：
### 1、在main.py中新增一行代码用于调用方法读取token，比如：_read_token
```
if __name__ == '__main__':
    # 在这里新增一行代码 比如 MapDataSolver() 用于获取游戏数据并更新本地文件，如果注释掉就走原来的逻辑
    sheep_solver = SheepSolver("normal", 0.8, True)
```

### 2、 _read_token方法获取token
获取用户控制台输入的token，或者让用户在项目中新建一个文件保存token避免每次都要输入

### 3、参考 automatic.DataAnalyzer.DataAnalyzer.response 方法，新增一个方法（比如叫：_get_map_data）获取游戏数据
现在的参数 flow 是开始游戏后获取的地图信息，用js写的话是这样的：
```
const url = `https://cat-match.easygame2021.com/sheep/v1/game/map_info_ex?matchType=3`;
const method = `GET`;
const headers = {
    'Accept-Encoding': `gzip,compress,br,deflate`,
    'content-type': `application/json`,
    'Connection': `keep-alive`,
    'Referer': `https://servicewechat.com/wx141bfb9b73c970a9/29/page-frame.html`,
    't': `你的t值`,
    'Host': `cat-match.easygame2021.com`,
    'User-Agent': `Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.29(0x18001d25) NetType/4G Language/zh_CN`
};
const body = ``;

const myRequest = {
    url: url,
    method: method,
    headers: headers,
    body: body
};

$task.fetch(myRequest).then(response => {
    console.log(response.statusCode + "\n\n" + response.body);
    $done();
}, reason => {
    console.log(reason.error);
    $done();
});

```
返回的信息是：
```
{
  "err_code" : 0,
  "err_msg" : "",
  "data" : {
    "map_md5" : [
      "046ef1bab26e5b9bfe2473ded237b572",
      "d9d5f97bbf1c587b34da2120da77c22e"
    ],
    "map_seed" : [
      4232401885,
      132803809,
      1943796078,
      1076140864
    ],
    "map_seed_2" : "1665528879"
  }
}

```
如上，实现上面的js功能，就能像automatic.DataAnalyzer.DataAnalyzer.response 方法一样， _get_map_data接着调用automatic.DataAnalyzer.DataAnalyzer._handle_response_result方法，后面的代码基本就是通用的啦

>上面的步骤走完以后本地文件中的游戏数据就更新了

### 4、main方法接着调用SheepSolver("normal", 0.8, True)，代码不用动。

**Comment by NB-Dragon** [comment]
你说的这个细节，上个月我就有实现了，给定一个token直到通关的流程，并且已经很稳定了。但是考虑到受众问题，不会对其进行公开，有需要的话，你可以进群付费体验。你要知道的是，不是每个用户都能清楚知道token怎么获取的

**Comment by fmz200** [comment]
OK
