### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by 499753506** [NB-Dragon/SheepSolver#13]
大佬，这个证书终端是放在Linux里面还是Windows，复制Linux怎么抓包，微信小程序是在Windows里面启动吗？499753506@qq.com
谢谢大佬，可以加一下

**Comment by NB-Dragon** [comment]
请先自学相关的抓包教程，掌握基本原理后再进行操作

**Comment by NB-Dragon** [comment]
简单来说，你用什么设备玩游戏，就装在什么设备上。

**Comment by 499753506** [comment]
输入mitmdump -p 6666 -s automatic/DataAnalyzer.py一直提示
in script automatic/DataAnalyzer.py: No module named 'hepler'
我找了方法也没有解决Windows的

**Comment by NB-Dragon** [comment]
> 输入mitmdump -p 6666 -s automatic/DataAnalyzer.py一直提示 in script automatic/DataAnalyzer.py: No module named 'hepler' 我找了方法也没有解决Windows的

新版本已适配好，不再需要配置临时变量了
