### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 499753506** [NB-Dragon/SheepSolver#15]
输入mitmweb -p 6666 -s automatic/DataAnalyzer.py一直提示
in script automatic/DataAnalyzer.py: No module named 'hepler'
用的是Windows系统，要怎么办

**Comment by NB-Dragon** [comment]
请仔细查看文档说明

**Comment by NB-Dragon** [comment]
更新页面，新版已经调整了启动策略，不再需要配置环境了

**Comment by 499753506** [comment]
一般解不开是，重新选择算法，还是重新抓地图数据

**Comment by NB-Dragon** [comment]
都行，看你怎么选
