### ISSUE TITLE
「建议」大佬持续优化算法，提升解题的成功率和速度

### ISSUE THREAD

**Issue by fmz200** [NB-Dragon/SheepSolver#17]
现在解题好慢啊，根本解不出来😅

**Comment by iversonpuppets** [comment]
解不出来因为有些局是死局，换张图或者换个模式再试试。

**Comment by AEPAX** [comment]
我也是解不出来，难度有点高

**Comment by fmz200** [comment]
> 

算法问题

**Comment by AEPAX** [comment]
的确，单单的回溯跟暴力破解没啥区别了。最好是能找到一个参数修改成分支限界

**Comment by rexjianer** [comment]
我提出一个思路，就是判断一个牌，按照这遮挡牌的数量来排序。
即子节点最多的牌，优先移出。
感觉现在这种按照序号的方案不是最优解。

**Comment by NB-Dragon** [comment]
> 我提出一个思路，就是判断一个牌，按照这遮挡牌的数量来排序。 即子节点最多的牌，优先移出。 感觉现在这种按照序号的方案不是最优解。

效果与高层优先等同，忽略该方案

**Comment by AEPAX** [comment]
目前top-first的效率算力是最高的吗

**Comment by iversonpuppets** [comment]
我会直接开4个，看哪个先跑完
反正都是单线程运行，不影响系统
但是内存得够

**Comment by AEPAX** [comment]
> 我会直接开4个，看哪个先跑完 反正都是单线程运行，不影响系统 但是内存得够

我没算玩过啊，你大概需要算多久

**Comment by AEPAX** [comment]
大佬也可以加一个多线程的启动项选项可以根据自己电脑设置一下线程数应该还能快不少

**Comment by NB-Dragon** [comment]
> 大佬也可以加一个多线程的启动项选项可以根据自己电脑设置一下线程数应该还能快不少

你应该是不懂什么是多线程。目前程序在单线程的算力下，已充份利用可用的CPU资源，多线程没有优化空间
