### ISSUE TITLE
今天无解啊 算不出来

### ISSUE THREAD

**Issue by f13098804603** [NB-Dragon/SheepSolver#2]
很难

**Comment by sunkr1995** [comment]
魔改呗 
ResidualPool里is_pool_full 改成len(self._pool_card.keys()) >= 6

class SheepSolver里solve的self._situation_history给用上
head_list 优先取高层卡片

再加个进度超过85%， 移除手牌前三张。
基本就过了

**Comment by coolerpluto** [comment]
> 

大佬改一下发布出来，谢谢哈

**Comment by anymine94** [comment]
> 魔改呗 ResidualPool里is_pool_full 改成len(self._pool_card.keys()) >= 6
> 
> class SheepSolver里solve的self._situation_history给用上 head_list 优先取高层卡片
> 
> 再加个进度超过85%， 移除手牌前三张。 基本就过了

大佬能不能改一个发出来谢谢了

**Comment by NB-Dragon** [comment]
> 

好想法，整完试试，对比解答时间。example里面有不同用时样本

**Comment by longhuan1999** [comment]
用example里面不同用时样本测试发现：
[item/ResidualPool.py](https://github.com/longhuan1999/sheep/blob/php/item/ResidualPool.py)
```
def is_pool_full(self):
        return len(self._pool_card.keys()) >= 6 or self._pool_count >= self._pool_limit
```
添加 len(self._pool_card.keys()) >= 6 条件能提高速度。

[business/SheepSolver.py](https://github.com/longhuan1999/sheep/blob/php/business/SheepSolver.py)
```
def solve(self, issort, percent):
        #print("\r当前进度为: {}/{}".format(len(self._pick_list), self._card_count), end="")
```
将 solve里的进度显示去掉，换成在外面倒计时也能提高速度。

---

优先取高层卡片，我还没真正做出来，但简单粗暴的对`head_list`从大到小排序，并不会提高example里面不同用时样本的速度，反而有可能会拖慢，不过有概率在短时间内解出其他关卡，配合默认方式同时进行能提高在短时间内解出关卡的概率。

进度超过85%， 移除手牌前三张，我也还没真正做出来，猜测应该能提高在进度后期的求解速度。

**Comment by sunkr1995** [comment]
> 
优先取高层卡片我觉得就是 把 head_list 改成从大到小的排列，因为在注册卡片时，是从低到高注册的，像近两天的题目中，低层卡片较少，高层卡片较多的情况，会提高解出关卡的速度。

移除手牌前三张，我的想法是记录进度的最大值，当进度达到80% ~ 90% 时，移出手牌中前三张，注册为新卡片放入 cardposition._other_data里，
def get_head_key_list(self):
        return list(self._head_data.keys()).expend(self._other_data.keys())
但我不会java，只能粗暴的在应该移出时 print信息。
这种方式基本是进度达到剩15~20张卡片时可以秒解。

**Comment by sunkr1995** [comment]
> 用example里面不同用时样本测试发现： [item/ResidualPool.py](https://github.com/longhuan1999/sheep/blob/autoSolver-php/item/ResidualPool.py)
> 
> ```
> def is_pool_full(self):
>         return len(self._pool_card.keys()) >= 6 or self._pool_count >= self._pool_limit
> ```
> 
> 添加 len(self._pool_card.keys()) >= 6 条件能提高速度。
> 
> [business/SheepSolver.py](https://github.com/longhuan1999/sheep/blob/autoSolver-php/business/SheepSolver.py)
> 
> ```
> def solve(self, issort, percent):
>         #print("\r当前进度为: {}/{}".format(len(self._pick_list), self._card_count), end="")
> ```
> 
> 将 solve里的进度显示去掉，换成在外面倒计时也能提高速度。
> 
> 优先取高层卡片，我还没真正做出来，但简单粗暴的对`head_list`从大到小排序，并不会提高example里面不同用时样本的速度，反而有可能会拖慢，不过有概率在短时间内解出其他关卡，配合默认方式同时进行能提高在短时间内解出关卡的概率。
> 
> 进度超过85%， 移除手牌前三张，我也还没真正做出来，猜测应该能提高在进度后期的求解速度。

我看你的工作比我进行的优秀多了

**Comment by longhuan1999** [comment]
> > 用example里面不同用时样本测试发现： [item/ResidualPool.py](https://github.com/longhuan1999/sheep/blob/autoSolver-php/item/ResidualPool.py)
> > ```
> > def is_pool_full(self):
> >         return len(self._pool_card.keys()) >= 6 or self._pool_count >= self._pool_limit
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 添加 len(self._pool_card.keys()) >= 6 条件能提高速度。
> > [business/SheepSolver.py](https://github.com/longhuan1999/sheep/blob/autoSolver-php/business/SheepSolver.py)
> > ```
> > def solve(self, issort, percent):
> >         #print("\r当前进度为: {}/{}".format(len(self._pick_list), self._card_count), end="")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 将 solve里的进度显示去掉，换成在外面倒计时也能提高速度。
> > 优先取高层卡片，我还没真正做出来，但简单粗暴的对`head_list`从大到小排序，并不会提高example里面不同用时样本的速度，反而有可能会拖慢，不过有概率在短时间内解出其他关卡，配合默认方式同时进行能提高在短时间内解出关卡的概率。
> > 进度超过85%， 移除手牌前三张，我也还没真正做出来，猜测应该能提高在进度后期的求解速度。
> 
> 我看你的工作比我进行的优秀多了

没有没有，他的算法我没改多少，我主要还是将抓包、求解和展示串联成一个流程

**Comment by NB-Dragon** [comment]
讨论中提及的优化方案，已经根据测试情况融入到该提交中
`commit: 1bdfba893028f1835d86ca15b9d19bdc87581dea`
用户可以根据实际情况选择
