### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hbpcj** [NB-Dragon/SheepSolver#22]
in script capture.py: 'NoneType' object is not subscriptable

**Comment by NB-Dragon** [comment]
Why don't you use the stable version?

**Comment by NB-Dragon** [comment]
How can I know how this problem occurred from your brief content?

**Comment by hbpcj** [comment]
Traceback (most recent call last):
  File "D:\SheepSolver\capture.py", line 53, in <module>
    addons = [DataAnalyzer()]
  File "D:\SheepSolver\capture.py", line 14, in __init__
    self._interface_tool = self._generate_interface_tool()
  File "D:\SheepSolver\capture.py", line 30, in _generate_interface_tool
    link_config = self._project_helper.get_project_config()["link"]
TypeError: 'NoneType' object is not subscriptable

**Comment by hbpcj** [comment]
找到问题了， windows 加上这就好了，FileHelper 第22行修改成这样reader = open(file_path, "r", encoding="UTF-8")

**Comment by NB-Dragon** [comment]
新版已添加默认编码
