### ISSUE TITLE
针对一直跑不出解的关卡通关思路

### ISSUE THREAD

**Issue by Angusvencent** [NB-Dragon/SheepSolver#4]
您好，能不能新增一个算法，针对何难求解的关卡。使用正序求解高层优先，求解进度大概超过0.92-0.95，就输出有解，保存并发送操作步骤，剩下的十来步操作可以用三个道具辅助人工完成通关。移出和复活有6个格子，加上本身本身的7个格子和打乱道具，应该可以通关。

**Comment by NB-Dragon** [comment]
1: 本开源算法只用于0道具实现通关
2: 该思路没有证明能有效提升解题速度，故不采纳
3: 算法已开源，要是不会改可向我定制费用
