### ISSUE TITLE
卡在online_data.json更新那一步

### ISSUE THREAD

**Issue by lon91ong** [NB-Dragon/SheepSolver#6]
使用PC端的微信，数据包也成功抓到了，但是online_data.json文件毫无动静

**Comment by lon91ong** [comment]
应该是mitmproxy设置有问题，抓包了一堆http协议，没抓到https的，如下图：
![只抓到了http协议数据](https://user-images.githubusercontent.com/16462258/197180134-ba5b5699-67d3-4356-8830-6b3c5c4854a0.png)
问题是mitmproxy要如何设置才能抓包https呢？

**Comment by lon91ong** [comment]
参考[#16](https://github.com/BugMaker888/sheep/issues/16), 以及 mitmproxy[说明](https://www.huoban.com/news/post/6210.html)、[参数配置](https://codeantenna.com/a/vELFYho6ll)
目前看来，[小程序抓包](https://blog.csdn.net/weixin_46552558/article/details/124037807)还得靠[HTTP Debugger](http://www.dayanzai.me/http-debugger.html)

**Comment by lon91ong** [comment]
参考[fiddler抓小程序的操作](https://blog.csdn.net/weixin_46552558/article/details/124037807), 修改WMPFRuntime文件夹只读并拒绝写入之后, 微信退回[3.7.5.25版本](https://myqqjd.lanzout.com/b06llxagd)小程序可以正常运行, 之后用mitmproxy做系统代理, 可以成功抓包.

**Comment by NB-Dragon** [comment]
认真看文档，按着步骤来。
