### ISSUE TITLE
牛逼，大佬又更新了、

### ISSUE THREAD

**Issue by lifengbing** [NB-Dragon/SheepSolver#7]

**Comment by samhuileo** [comment]
大佬能不能考虑一下计算使用道具的算法（移出和复活），今天我跑了一个小时还是解不出，人手解靠着两个道具就可以了。

**Comment by NB-Dragon** [comment]
> 大佬能不能考虑一下计算使用道具的算法（移出和复活），今天我跑了一个小时还是解不出，人手解靠着两个道具就可以了。

本算法的宗旨就是不用道具通关，这个话题不用再提。
最新版提供随机模式，多试几次会有奇效

**Comment by wzgy** [comment]
> 大佬能不能考虑一下计算使用道具的算法（移出和复活），今天我跑了一个小时还是解不出，人手解靠着两个道具就可以了。

用上道具直接动摇了动态规划的根基，改就是重新找算法了，如果用经验参数，那就太玄学了
