### ISSUE TITLE
最新版使用体验

### ISSUE THREAD

**Issue by Fireky1in** [NB-Dragon/SheepSolver#8]
解法加强了，800秒可跑出今日的话题关卡，普通关卡 60秒左右
但是生成的数据文件 被压塑需要还原然后魔改 才能用在第三方web自动解 网页，yin'we
输出的倒数第第二行是post提交数据

建议和3d地图版 完美结合直接 如果跑出来结果直接写入 js 刷新

**Comment by NB-Dragon** [comment]
这次改版之后，后续不再进行数据融合了，已经彻底自主可控。
改版后依旧保留答题步骤的输出，不过需要手动进行答案融合。

**Comment by rexjianer** [comment]
> 解法加强了，800秒可跑出今日的话题关卡，普通关卡 60秒左右 但是生成的数据文件 被压塑需要还原然后魔改 才能用在第三方web自动解 网页，yin'we 输出的倒数第第二行是post提交数据
> 
> 建议和3d地图版 完美结合直接 如果跑出来结果直接写入 js 刷新

我以为是优化了算法，结果今天算不出来。2022.11.1

**Comment by wzgy** [comment]
> 
周末一般都简单，这周周一也简单，
运算量在那儿，出题者减小横截面、增加种类、减少每种牌的数量，运算量直接就爆炸了

**Comment by wzgy** [comment]
> > 解法加强了，800秒可跑出今日的话题关卡，普通关卡 60秒左右 但是生成的数据文件 被压塑需要还原然后魔改 才能用在第三方web自动解 网页，yin'we 输出的倒数第第二行是post提交数据
> > 建议和3d地图版 完美结合直接 如果跑出来结果直接写入 js 刷新
> 
> 我以为是优化了算法，结果今天算不出来。2022.11.1

周末一般都简单，这周周一也简单，
运算量在那儿，出题者减小横截面、增加种类、减少每种牌的数量，运算量直接就爆炸了

**Comment by lsdlh** [comment]
> 此次改版之后，不再数据融合了，已经自主管理。 改版后仍保留修改答案的问题步骤的输出，但需要手动进行融合。

我直接请求地图接口获得数据写入online_data.json，然后运行main默认模式跑，怎么计算用时: 0.005970954895019531就算完了，算出的结果回显步骤也不对

**Comment by rexjianer** [comment]
> > 此次改版之后，不再数据融合了，已经自主管理。 改版后仍保留修改答案的问题步骤的输出，但需要手动进行融合。
> 
> 我直接请求地图接口获得数据写入online_data.json，然后运行main默认模式跑，怎么计算用时: 0.005970954895019531就算完了，算出的结果回显步骤也不对

因为你算出来的是默认的地图，255个图案那个版本。

**Comment by Fireky1in** [comment]
今天的谁跑出来了，欢迎来交流
https://t.me/yanglegeyangsuanfa

**Comment by lifengbing** [comment]
还是喜欢原版，可以跟游戏界面交互，多少有一些参与感。完全自动化感觉就没意思了。

**Comment by lifengbing** [comment]
> 今天的谁跑出来了，欢迎来交流 https://t.me/yanglegeyangsuanfa

打不开有其他群没有呀。

**Comment by Fireky1in** [comment]
> > 今天的谁跑出来了，欢迎来交流 https://t.me/yanglegeyangsuanfa
> 
> 打不开有其他群没有呀。

翻墙打开

**Comment by lifengbing** [comment]
> > > 今天的谁跑出来了，欢迎来交流 https://t.me/yanglegeyangsuanfa
> > 
> > 
> > 打不开有其他群没有呀。
> 
> 翻墙打开

不敢翻

**Comment by Fireky1in** [comment]
> 这次改版之后，后续不再进行数据融合了，已经彻底自主可控。 改版后依旧保留答题步骤的输出，不过需要手动进行答案融合。

大佬 今天更新代码了吗？可以来tg群交流下https://t.me/yanglegeyangsuanfa

**Comment by doris8989** [comment]
谁可以帮我电脑装一个这个项目的运行，我自己整了好久弄不起来，有偿

**Comment by doris8989** [comment]
> 这次改版之后，后续不再进行数据融合了，已经彻底自主可控。
> 改版后依旧保留答题步骤的输出，不过需要手动进行答案融合。

能不能帮我设置一下，有偿

**Comment by Fireky1in** [comment]
> 谁可以帮我电脑装一个这个项目的运行，我自己整了好久弄不起来，有偿

这很难吗？
![Uploading 23791E96-5DD5-4050-BA7F-8D5DD361227F.png…]()

**Comment by Fireky1in** [comment]
> 会翻墙吗可以来tg群交流下https://t.me/yanglegeyangsuanfa
不会留下qq我➕你

**Comment by Fireky1in** [comment]
> > 这次改版之后，后续不再进行数据融合了，已经彻底自主可控。
> > 改版后依旧保留答题步骤的输出，不过需要手动进行答案融合。
> 
> 能不能帮我设置一下，有偿

有偿


> 谁可以帮我电脑装一个这个项目的运行，我自己整了好久弄不起来，有偿

会翻墙吗可以来tg群交流下https://t.me/yanglegeyangsuanfa
不会留下qq我➕你

**Comment by doris8989** [comment]
> 

379781385

**Comment by jiangyanfeng** [comment]
能否支持一下顶三张和复活？感觉纯不看广告的话，电脑跑到冒烟都回溯不出结果。

**Comment by NB-Dragon** [comment]
> 

原版的功能还是保留着，用更新的online_data.json，加上结果，转换成地图版的js文件即可

**Comment by NB-Dragon** [comment]
> 还是喜欢原版，可以跟游戏界面交互，多少有一些参与感。完全自动化感觉就没意思了。


原版的功能还是保留着，用更新的online_data.json，加上结果，转换成3D版的js文件即可

**Comment by NB-Dragon** [comment]
> > 此次改版之后，不再数据融合了，已经自主管理。 改版后仍保留修改答案的问题步骤的输出，但需要手动进行融合。
> 
> 我直接请求地图接口获得数据写入online_data.json，然后运行main默认模式跑，怎么计算用时: 0.005970954895019531就算完了，算出的结果回显步骤也不对

因为你这个接口数据没有卡牌类型，初始情况下全是0，也就是说游戏中的牌只有一种，当然用时少了。
@lsdlh @rexjianer

**Comment by heimaobaifanfan** [comment]
大佬，运行mitmdump -p 6666 -s automatic/DataAnalyzer.py后一直报错。
in script automatic/DataAnalyzer.py: No module named 'automatic'
Proxy server listening at *:6666

我看了路径下面是有这个文件的

C:\Windows\System32\SheepSolver\automatic

请问这个是哪里的问题“”

**Comment by Fireky1in** [comment]
> SheepSolver
环境变量

**Comment by Fireky1in** [comment]
> 大佬，运行mitmdump -p 6666 -s automatic/DataAnalyzer.py后一直报错。 in script automatic/DataAnalyzer.py: No module named 'automatic' Proxy server listening at *:6666
> 
> 我看了路径下面是有这个文件的
> 
> C:\Windows\System32\SheepSolver\automatic
> 
> 请问这个是哪里的问题“”

配置环境变量export PYTHONPATH="SheepSolver绝对路径"

**Comment by lifengbing** [comment]
今天好难啊85%都跑不到。。。

**Comment by heimaobaifanfan** [comment]
win10下面set PYTHONPATH=C:\Windows\System32\SheepSolver  这么设置环境变量合适吗？

**Comment by lsdlh** [comment]
> > > 此次改版之后，不再数据融合了，已经自主管理。 改版后仍保留修改答案的问题步骤的输出，但需要手动进行融合。
> > 
> > 
> > 我直接请求地图接口获得数据写入online_data.json，然后运行main默认模式跑，怎么计算用时: 0.005970954895019531就算完了，算出的结果回显步骤也不对
> 
> 因为你这个接口数据没有卡牌类型，初始情况下全是0，也就是说游戏中的牌只有一种，当然用时少而且步骤错误了。 @lsdlh @rexjianer

明白了谢谢

**Comment by heimaobaifanfan** [comment]
不对，我在cmd中可以用set path设置环境变量，但是Anaconda Powershell Prompt 这个下面设置不了，有没有大佬知道一下，怎么在Anaconda Powershell Prompt 中设置环境变量

**Comment by heimaobaifanfan** [comment]
> 



> > 大佬，运行mitmdump -p 6666 -s automatic/DataAnalyzer.py后一直报错。 in script automatic/DataAnalyzer.py: No module named 'automatic' Proxy server listening at *:6666
> > 我看了路径下面是有这个文件的
> > C:\Windows\System32\SheepSolver\automatic
> > 请问这个是哪里的问题“”
> 
> 配置环境变量export PYTHONPATH="SheepSolver绝对路径"

我用的是win系统，Anaconda Powershell Prompt (这个下面运行的，使用了set path但是只能在cmd中设置环境变量。，Anaconda Powershell Prompt 里面没有办法设置。

**Comment by NB-Dragon** [comment]
> 不对，我在cmd中可以用set path设置环境变量，但是Anaconda Powershell Prompt 这个下面设置不了，有没有大佬知道一下，怎么在Anaconda Powershell Prompt 中设置环境变量

哪个能用就用哪个，有什么好纠结的呢

**Comment by jiangyanfeng** [comment]
今天的很快就跑出结果了。

**Comment by rexjianer** [comment]
要麻烦大神更一下两次移三张的算法，现在的难度，每周能解出来一天。

**Comment by NB-Dragon** [comment]
> 要麻烦大神更一下两次移三张的算法，现在的难度，每周能解出来一天。

可是我都连续通关5天了。这个功能就让你来实现吧，本项目的宗旨就是不用道具

**Comment by leeso2021** [comment]
> > 要麻烦大神更一下两次移三张的算法，现在的难度，每周能解出来一天。
> 
> 
> 
> 可是我都连续通关5天了。这个功能就让你来实现吧，本项目的宗旨就是不用道具

大佬一般用什么模式解。。。

**Comment by lifengbing** [comment]
> 要麻烦大神更一下两次移三张的算法，现在的难度，每周能解出来一天。

天天双杀，人家代码非常好用、

**Comment by NB-Dragon** [comment]
> > > 要麻烦大神更一下两次移三张的算法，现在的难度，每周能解出来一天。
> > 
> > 
> > 可是我都连续通关5天了。这个功能就让你来实现吧，本项目的宗旨就是不用道具
> 
> 大佬一般用什么模式解。。。

4种都用

**Comment by leeso2021** [comment]
刚研究好自动提交的代码，大佬就更新自动提交~

**Comment by lon91ong** [comment]
希望能添加函数功能、参数的注释说明，方便更多的人逆向参与到算法的改进当中

**Comment by NB-Dragon** [comment]
> 希望能添加函数功能、参数的注释说明，方便更多的人逆向参与到算法的改进当中

注释是不可能加的，这辈子都是不可能的。
函数的功能都已经用英文写在函数名称上了，具体逻辑只要懂Python基础的都能看懂。
